In [49]:
#import important libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
import pandas as pd
from sklearn.cluster import SpectralClustering
#dataset=pd.read_csv("urbanGB.csv")
from numpy import genfromtxt
dataset = genfromtxt('urbanGB.csv', delimiter=',', skip_header = 1)
spectral_dataset=[]
for n in range(1000):
    spectral_dataset.append(dataset[n])
s_dataset=np.array(spectral_dataset)

In [50]:
float_formatter = lambda x: "%.3f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})
from sklearn.cluster import SpectralClustering, KMeans
from sklearn.metrics import pairwise_distances
from matplotlib import pyplot as plt
import networkx as nx
import seaborn as sns
sns.set()

In [51]:
#calculating weight matrix on the basis of euclidean distance
W = pairwise_distances(s_dataset, metric="euclidean")
vectorizer = np.vectorize(lambda x: 1 if x < 5 else 0)
#avoiding fully connected graph
W = np.vectorize(vectorizer)(W)
print(W)

[[1 0 0 ... 1 0 0]
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]


In [52]:
# degree matrix
D = np.diag(np.sum(W, axis=1))
D

array([[608,   0,   0, ...,   0,   0,   0],
       [  0, 937,   0, ...,   0,   0,   0],
       [  0,   0, 941, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 945,   0,   0],
       [  0,   0,   0, ...,   0, 923,   0],
       [  0,   0,   0, ...,   0,   0, 938]])

In [53]:
# laplacian matrix
L = D - W
print('laplacian matrix:')
print(L)

laplacian matrix:
[[607   0   0 ...  -1   0   0]
 [  0 936  -1 ...  -1  -1  -1]
 [  0  -1 940 ...  -1  -1  -1]
 ...
 [ -1  -1  -1 ... 944  -1  -1]
 [  0  -1  -1 ...  -1 922  -1]
 [  0  -1  -1 ...  -1  -1 937]]


In [54]:
e, v = np.linalg.eig(L)
e = e.real
v = v.real

In [55]:
v.shape

(1000, 1000)

In [56]:
U=[]
clusters=4
for i in range(clusters):
    U.append(v[i])
U=np.array(U)
U.shape

(4, 1000)

In [57]:
U

array([[0.032, -0.002, -0.002, ..., 0.000, -0.000, 0.000],
       [0.032, 0.002, -0.002, ..., 0.000, -0.000, 0.000],
       [0.032, 0.002, -0.002, ..., 0.000, -0.000, 0.000],
       [0.032, 0.001, 0.000, ..., 0.000, -0.000, 0.000]])

In [58]:
U=U.T
U.shape

(1000, 4)

In [59]:
U

array([[0.032, 0.032, 0.032, 0.032],
       [-0.002, 0.002, 0.002, 0.001],
       [-0.002, -0.002, -0.002, 0.000],
       ...,
       [0.000, 0.000, 0.000, 0.000],
       [-0.000, -0.000, -0.000, -0.000],
       [0.000, 0.000, 0.000, 0.000]])

In [60]:
from sklearn.cluster import KMeans
#creating a k-means object
k_Means_Obj=KMeans(n_clusters=4)

In [61]:
import time
start = time.time()
k_Means_Obj.fit(U)
end = time.time()

In [62]:
clusters=k_Means_Obj.cluster_centers_

In [63]:
clusters

array([[-0.000, 0.001, -0.001, -0.002],
       [-0.000, 0.946, 0.000, 0.000],
       [-0.000, -0.000, 0.972, -0.000],
       [0.650, -0.000, -0.000, 0.000]])

In [64]:
final=k_Means_Obj.fit_predict(U)

In [67]:
#assigned cluster number
final.shape

(1000,)